export default function HowItWorksContent({ user }) {

    return (

        <div className="py-12">
            <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div className="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
                    <div className="p-6 bg-red-50 dark:bg-red-800/20 text-white text-2xl font-bold">
                        How It Works
                    </div>

                    <div className="p-6 text-gray-900 dark:text-gray-100">
                        Must Watch Sports is a college football game ranking service that uses an algorithm to rate and rank
                        every D1 college football game of the season. The goal is to help you find the best games to watch without
                        spoiling anything about the game itself. The ranking is broadly divided into five categories:
                    </div>

                    <div className="p-6 text-gray-900 dark:text-gray-100">
                        The first and maybe most important is generated by calculating how much of 
                        the game was close OR by whether the team that was losing was able to make a comeback. This is modified with a bonus if 
                        the game was closer than the betting spread because overachieving underdogs are awesome. (Sorry if that offends ESPN).
                    </div>

                    <div className="p-6 text-gray-900 dark:text-gray-100">
                        The second part is the importance of the game. This is generated very simply by looking at historical record over the last
                        few years (early in the season) and later by looking at the teams record for the year once more games have been played. After the
                        year is over this rating is finalized with end of year results.
                    </div>

                    <div className="p-6 text-gray-900 dark:text-gray-100">
                        The third rating is the explosive plays rating. Great games have big plays and this rating is created by 
                        iterating through each play of the game and adding to an explosiveness score when chunk plays, scores, 
                        turnovers, sacks and other big plays happen. This is weighted to try to make a score approaching 100 rare.
                    </div>

                    <div className="p-6 text-gray-900 dark:text-gray-100">
                        Next is the talent composite score of the two teams. All things being equal, great athletes make amazing plays which
                        makes great games. More talent being on the field trends towards a more entertaining game. This rating is pulled from College
                        Football API that tracks overall team talent (through rating services).
                    </div>

                    <div className="p-6 text-gray-900 dark:text-gray-100">
                        The final and least important rating is for how many penalties occur in the game. This is weighted the least heavily 
                        but if I have to choose between no penalties and lots of penalties that choice is pretty easy.
                    </div>

                    <div className="p-6 text-gray-900 dark:text-gray-100">
                        These ratings are weighted and added together to form a total composite ranking which is the order that games are ranked by. 
                        If you make a profile you can weight the scores differently. Please send any suggestions or requests to{' '}
                        <a href="mailto:taylorb@mustwatchsports.com" className="text-blue-600 dark:text-blue-400 hover:underline">
                            taylorb@mustwatchsports.com
                        </a>.
                    </div>

                    <div className="p-6 bg-red-50 dark:bg-red-800/20 text-white text-2xl font-bold">
                        How It Started
                    </div>

                    <div className="p-6 text-gray-900 dark:text-gray-100">
                        Hi, I'm Taylor 👋. I have always loved two things: college football and weekends. A good chunk of my life has been about  
                        maximizing both. Must Watch Sports was built to highlight the most enjoyable games on TV on a Saturday so that I could spend
                        early Saturdays doing whatever I would like to then cram the best four games of the day back to back.
                    </div>
                    <div className="p-6 text-gray-900 dark:text-gray-100">
                        I made the algorithm just for me when I was learning to code so that I could record every game and then watch the best ones without
                        having to sit through commercials. When I was interviewing around I made a website to display the rankings for a portfolio piece. 
                    </div>

                    <div className="p-6 text-gray-900 dark:text-gray-100">
                        These days the split screen is good enough that I do end up just watching football all day most game days but I still enjoy
                        seeing which games are rated the highest and re-living the best moments of the day. If this site helps you to enjoy football more
                        or gives you some fun rankings to look at then I am super happy about that. Please reach out with any ideas or feedback or questions (or job offers 🤞)
                        to{' '}
                        <a href="mailto:taylorb@mustwatchsports.com" className="text-blue-600 dark:text-blue-400 hover:underline">
                            taylorb@mustwatchsports.com
                        </a>.
                    </div>
                </div>
            </div>
        </div>
    );
}